spring:
  profiles:
    group:
      local: prod
#custom:
#  url: ${AWS_URL}
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: ${AWS_DB_DRIVER}
    url: ${AWS_DB_URL}
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    aws:
      credentials:
        accessKey: ${ACCESSKEY}
        secretKey: ${SECRETKEY}
      s3:
        bucket: ${BUCKET}
      region:
        static: ${STATIC_REGION}
  jwt:
    secret: ${SECRET_KEY}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
